set_property PACKAGE_PIN AF14 [get_ports sys_clk_in_p]
set_property PACKAGE_PIN AJ30 [get_ports rtc_sclk]
set_property PACKAGE_PIN AK30 [get_ports rtc_io]
set_property PACKAGE_PIN AJ28 [get_ports rtc_ce]
set_property IOSTANDARD LVCMOS33 [get_ports rtc_ce]
set_property IOSTANDARD LVCMOS33 [get_ports rtc_io]
set_property IOSTANDARD LVCMOS33 [get_ports rtc_sclk]
set_property IOSTANDARD LVDS_25 [get_ports sys_clk_in_p]
set_property IOSTANDARD LVDS_25 [get_ports sys_clk_in_n]

create_clock -period 5.000 -name sys_clk_in -waveform {0.000 2.500} -add [get_ports sys_clk_in_p]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk_in_BUFG]
